// flow-typed signature: 2058273691b5f48868c7bbcaa8bd46bb
// flow-typed version: <<STUB>>/exp_v^55.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exp/bin/exp' {
  declare module.exports: any;
}

declare module 'exp/build/accounts' {
  declare module.exports: any;
}

declare module 'exp/build/askUser' {
  declare module.exports: any;
}

declare module 'exp/build/CommandError' {
  declare module.exports: any;
}

declare module 'exp/build/commands/android' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/AndroidBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/auth' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/BaseBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/BuildError' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/IOSBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/bundle-assets' {
  declare module.exports: any;
}

declare module 'exp/build/commands/diagnostics' {
  declare module.exports: any;
}

declare module 'exp/build/commands/doctor' {
  declare module.exports: any;
}

declare module 'exp/build/commands/fetch' {
  declare module.exports: any;
}

declare module 'exp/build/commands/init' {
  declare module.exports: any;
}

declare module 'exp/build/commands/install' {
  declare module.exports: any;
}

declare module 'exp/build/commands/ios' {
  declare module.exports: any;
}

declare module 'exp/build/commands/login' {
  declare module.exports: any;
}

declare module 'exp/build/commands/logout' {
  declare module.exports: any;
}

declare module 'exp/build/commands/prepare-detached-build' {
  declare module.exports: any;
}

declare module 'exp/build/commands/publish-info' {
  declare module.exports: any;
}

declare module 'exp/build/commands/publish-modify' {
  declare module.exports: any;
}

declare module 'exp/build/commands/publish' {
  declare module.exports: any;
}

declare module 'exp/build/commands/push-creds' {
  declare module.exports: any;
}

declare module 'exp/build/commands/register' {
  declare module.exports: any;
}

declare module 'exp/build/commands/send' {
  declare module.exports: any;
}

declare module 'exp/build/commands/url' {
  declare module.exports: any;
}

declare module 'exp/build/commands/utils/cli-table' {
  declare module.exports: any;
}

declare module 'exp/build/commands/whoami' {
  declare module.exports: any;
}

declare module 'exp/build/commonOptions' {
  declare module.exports: any;
}

declare module 'exp/build/debug_commands/sandbox' {
  declare module.exports: any;
}

declare module 'exp/build/debug_commands/vscode' {
  declare module.exports: any;
}

declare module 'exp/build/exit' {
  declare module.exports: any;
}

declare module 'exp/build/exp_commands/convert' {
  declare module.exports: any;
}

declare module 'exp/build/exp_commands/detach' {
  declare module.exports: any;
}

declare module 'exp/build/exp_commands/path' {
  declare module.exports: any;
}

declare module 'exp/build/exp_commands/start' {
  declare module.exports: any;
}

declare module 'exp/build/exp_commands/test-schema' {
  declare module.exports: any;
}

declare module 'exp/build/exp' {
  declare module.exports: any;
}

declare module 'exp/build/expo_commands/eject' {
  declare module.exports: any;
}

declare module 'exp/build/expo_commands/eject/Eject' {
  declare module.exports: any;
}

declare module 'exp/build/expo_commands/start' {
  declare module.exports: any;
}

declare module 'exp/build/log' {
  declare module.exports: any;
}

declare module 'exp/build/printRunInstructionsAsync' {
  declare module.exports: any;
}

declare module 'exp/build/prompt' {
  declare module.exports: any;
}

declare module 'exp/build/sendTo' {
  declare module.exports: any;
}

declare module 'exp/build/update' {
  declare module.exports: any;
}

declare module 'exp/build/urlOpts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exp/bin/exp.js' {
  declare module.exports: $Exports<'exp/bin/exp'>;
}
declare module 'exp/build/accounts.js' {
  declare module.exports: $Exports<'exp/build/accounts'>;
}
declare module 'exp/build/askUser.js' {
  declare module.exports: $Exports<'exp/build/askUser'>;
}
declare module 'exp/build/CommandError.js' {
  declare module.exports: $Exports<'exp/build/CommandError'>;
}
declare module 'exp/build/commands/android.js' {
  declare module.exports: $Exports<'exp/build/commands/android'>;
}
declare module 'exp/build/commands/build.js' {
  declare module.exports: $Exports<'exp/build/commands/build'>;
}
declare module 'exp/build/commands/build/AndroidBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/AndroidBuilder'>;
}
declare module 'exp/build/commands/build/auth.js' {
  declare module.exports: $Exports<'exp/build/commands/build/auth'>;
}
declare module 'exp/build/commands/build/BaseBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/BaseBuilder'>;
}
declare module 'exp/build/commands/build/BuildError.js' {
  declare module.exports: $Exports<'exp/build/commands/build/BuildError'>;
}
declare module 'exp/build/commands/build/IOSBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/IOSBuilder'>;
}
declare module 'exp/build/commands/bundle-assets.js' {
  declare module.exports: $Exports<'exp/build/commands/bundle-assets'>;
}
declare module 'exp/build/commands/diagnostics.js' {
  declare module.exports: $Exports<'exp/build/commands/diagnostics'>;
}
declare module 'exp/build/commands/doctor.js' {
  declare module.exports: $Exports<'exp/build/commands/doctor'>;
}
declare module 'exp/build/commands/fetch.js' {
  declare module.exports: $Exports<'exp/build/commands/fetch'>;
}
declare module 'exp/build/commands/init.js' {
  declare module.exports: $Exports<'exp/build/commands/init'>;
}
declare module 'exp/build/commands/install.js' {
  declare module.exports: $Exports<'exp/build/commands/install'>;
}
declare module 'exp/build/commands/ios.js' {
  declare module.exports: $Exports<'exp/build/commands/ios'>;
}
declare module 'exp/build/commands/login.js' {
  declare module.exports: $Exports<'exp/build/commands/login'>;
}
declare module 'exp/build/commands/logout.js' {
  declare module.exports: $Exports<'exp/build/commands/logout'>;
}
declare module 'exp/build/commands/prepare-detached-build.js' {
  declare module.exports: $Exports<'exp/build/commands/prepare-detached-build'>;
}
declare module 'exp/build/commands/publish-info.js' {
  declare module.exports: $Exports<'exp/build/commands/publish-info'>;
}
declare module 'exp/build/commands/publish-modify.js' {
  declare module.exports: $Exports<'exp/build/commands/publish-modify'>;
}
declare module 'exp/build/commands/publish.js' {
  declare module.exports: $Exports<'exp/build/commands/publish'>;
}
declare module 'exp/build/commands/push-creds.js' {
  declare module.exports: $Exports<'exp/build/commands/push-creds'>;
}
declare module 'exp/build/commands/register.js' {
  declare module.exports: $Exports<'exp/build/commands/register'>;
}
declare module 'exp/build/commands/send.js' {
  declare module.exports: $Exports<'exp/build/commands/send'>;
}
declare module 'exp/build/commands/url.js' {
  declare module.exports: $Exports<'exp/build/commands/url'>;
}
declare module 'exp/build/commands/utils/cli-table.js' {
  declare module.exports: $Exports<'exp/build/commands/utils/cli-table'>;
}
declare module 'exp/build/commands/whoami.js' {
  declare module.exports: $Exports<'exp/build/commands/whoami'>;
}
declare module 'exp/build/commonOptions.js' {
  declare module.exports: $Exports<'exp/build/commonOptions'>;
}
declare module 'exp/build/debug_commands/sandbox.js' {
  declare module.exports: $Exports<'exp/build/debug_commands/sandbox'>;
}
declare module 'exp/build/debug_commands/vscode.js' {
  declare module.exports: $Exports<'exp/build/debug_commands/vscode'>;
}
declare module 'exp/build/exit.js' {
  declare module.exports: $Exports<'exp/build/exit'>;
}
declare module 'exp/build/exp_commands/convert.js' {
  declare module.exports: $Exports<'exp/build/exp_commands/convert'>;
}
declare module 'exp/build/exp_commands/detach.js' {
  declare module.exports: $Exports<'exp/build/exp_commands/detach'>;
}
declare module 'exp/build/exp_commands/path.js' {
  declare module.exports: $Exports<'exp/build/exp_commands/path'>;
}
declare module 'exp/build/exp_commands/start.js' {
  declare module.exports: $Exports<'exp/build/exp_commands/start'>;
}
declare module 'exp/build/exp_commands/test-schema.js' {
  declare module.exports: $Exports<'exp/build/exp_commands/test-schema'>;
}
declare module 'exp/build/exp.js' {
  declare module.exports: $Exports<'exp/build/exp'>;
}
declare module 'exp/build/expo_commands/eject.js' {
  declare module.exports: $Exports<'exp/build/expo_commands/eject'>;
}
declare module 'exp/build/expo_commands/eject/Eject.js' {
  declare module.exports: $Exports<'exp/build/expo_commands/eject/Eject'>;
}
declare module 'exp/build/expo_commands/start.js' {
  declare module.exports: $Exports<'exp/build/expo_commands/start'>;
}
declare module 'exp/build/log.js' {
  declare module.exports: $Exports<'exp/build/log'>;
}
declare module 'exp/build/printRunInstructionsAsync.js' {
  declare module.exports: $Exports<'exp/build/printRunInstructionsAsync'>;
}
declare module 'exp/build/prompt.js' {
  declare module.exports: $Exports<'exp/build/prompt'>;
}
declare module 'exp/build/sendTo.js' {
  declare module.exports: $Exports<'exp/build/sendTo'>;
}
declare module 'exp/build/update.js' {
  declare module.exports: $Exports<'exp/build/update'>;
}
declare module 'exp/build/urlOpts.js' {
  declare module.exports: $Exports<'exp/build/urlOpts'>;
}
