// flow-typed signature: 3b052ac0f16d5c22879d96b64fe724a3
// flow-typed version: <<STUB>>/websql_v^1.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'websql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'websql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'websql/custom/index' {
  declare module.exports: any;
}

declare module 'websql/lib/browser' {
  declare module.exports: any;
}

declare module 'websql/lib/custom' {
  declare module.exports: any;
}

declare module 'websql/lib/index' {
  declare module.exports: any;
}

declare module 'websql/lib/sqlite/SQLiteDatabase' {
  declare module.exports: any;
}

declare module 'websql/lib/sqlite/SQLiteResult' {
  declare module.exports: any;
}

declare module 'websql/lib/websql/WebSQLDatabase' {
  declare module.exports: any;
}

declare module 'websql/lib/websql/WebSQLResultSet' {
  declare module.exports: any;
}

declare module 'websql/lib/websql/WebSQLTransaction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'websql/custom/index.js' {
  declare module.exports: $Exports<'websql/custom/index'>;
}
declare module 'websql/lib/browser.js' {
  declare module.exports: $Exports<'websql/lib/browser'>;
}
declare module 'websql/lib/custom.js' {
  declare module.exports: $Exports<'websql/lib/custom'>;
}
declare module 'websql/lib/index.js' {
  declare module.exports: $Exports<'websql/lib/index'>;
}
declare module 'websql/lib/sqlite/SQLiteDatabase.js' {
  declare module.exports: $Exports<'websql/lib/sqlite/SQLiteDatabase'>;
}
declare module 'websql/lib/sqlite/SQLiteResult.js' {
  declare module.exports: $Exports<'websql/lib/sqlite/SQLiteResult'>;
}
declare module 'websql/lib/websql/WebSQLDatabase.js' {
  declare module.exports: $Exports<'websql/lib/websql/WebSQLDatabase'>;
}
declare module 'websql/lib/websql/WebSQLResultSet.js' {
  declare module.exports: $Exports<'websql/lib/websql/WebSQLResultSet'>;
}
declare module 'websql/lib/websql/WebSQLTransaction.js' {
  declare module.exports: $Exports<'websql/lib/websql/WebSQLTransaction'>;
}
