import type { Leaf } from './Leaf'

export default ([
  {'type':'EsN',
    'en':'skin', 'es':'piel', 'gender':'F',
    'mnemonic':'skin is burnt and peeled'},
  {'type':'EsN',
    'en':'arm', 'es':'brazo', 'gender':'M',
    'mnemonic':'arm tan is bronze'},
  {'type':'EsN',
    'en':'leg', 'es':'pierna', 'gender':'F',
    'mnemonic':'leggo my leg or I\'ll pee urine'},
  {'type':'EsN', 'en':'heart', 'es':'corazón', 'gender':'M' },
  {'type':'EsN', 'en':'stomach', 'es':'estómago', 'gender':'M' },
  {'type':'EsN', 'en':'eye', 'es':'ojo', 'gender':'M' },
  {'type':'EsN', 'en':'nose', 'es':'nariz', 'gender':'F' },
  {'type':'EsN', 'en':'mouth', 'es':'boca', 'gender':'F' },
  {'type':'EsN',
    'en':'ear', 'es':'oreja', 'gender':'F',
    'mnemonic':'ear rings of oreos'},
  {'type':'EsN',
    'en':'face', 'es':'cara', 'gender':'F',
    'mnemonic':'face got cut off'},
  {'type':'EsN',
    'en':'neck', 'es':'cuello', 'gender':'M',
    'mnemonic':'neck vein was cut way open'},
  {'type':'EsN',
    'en':'finger', 'es':'dedo', 'gender':'M',
    'mnemonic':'finger technique by Dedone'},
  {'type':'EsN',
    'en':'foot', 'es':'pie', 'gender':'M',
    'mnemonic':'foot stays in the state of PA'},
  {'type':'EsN',
    'en':'thigh', 'es':'muslo', 'gender':'M',
    'mnemonic':'thigh-high boots from wild moose'},
  {'type':'EsN',
    'en':'ankle', 'es':'tobillo', 'gender':'M',
    'mnemonic':'ankle stung to be young'},
  {'type':'EsN',
    'en':'elbow', 'es':'codo', 'gender':'M',
    'mnemonic':'elbow dipped and coated'},
  {'type':'EsN',
    'en':'wrist', 'es':'muñeca', 'gender':'F',
    'mnemonic':'wrist watch says \'Moon not yet come!\''},
  {'type':'EsN',
    'en':'body', 'es':'cuerpo', 'gender':'M',
    'mnemonic':'body bag for corpse'},
  {'type':'EsN',
    'en':'tooth', 'es':'diente', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN',
    'en':'hand', 'es':'mano', 'gender':'F',
    'mnemonic':'hand me the manual'},
  {'type':'EsN',
    'en':'back', 'es':'espalda', 'gender':'F',
    'mnemonic':'back hair is bald'},
  {'type':'EsN',
    'en':'hip', 'es':'cadera', 'gender':'F',
    'mnemonic':'hipster can\'t dare'},
  {'type':'EsN',
    'en':'jaw', 'es':'mandíbula', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN',
    'en':'shoulder', 'es':'hombro', 'gender':'M',
    'mnemonic':'shoulder on, my brother'},
  {'type':'EsN',
    'en':'thumb', 'es':'pulgar', 'gender':'M',
    'mnemonic':'thumb war: push and pull hard'},
  {'type':'EsN',
    'en':'tongue', 'es':'lengua', 'gender':'F',
    'mnemonic':'tongue length for languages'},
  {'type':'EsN',
    'en':'throat', 'es':'garganta', 'gender':'F',
    'mnemonic':'throat can\'t gargle gargantuan'},
  {'type':'EsDUniq', 'en':'the', 'es':'el', 'gender':'M' },
  {'type':'EsDUniq', 'en':'the', 'es':'la', 'gender':'F' },
  {'type':'EsDUniq', 'en':'a', 'es':'un', 'gender':'M' },
  {'type':'EsDUniq', 'en':'a', 'es':'una', 'gender':'F' },
  {'type':'EsDUniq', 'en':'my', 'es':'mi', 'gender':'' },
  {'type':'EsDUniq', 'en':'every', 'es':'cada', 'gender':'' },
  {'type':'EsDMorpheme', 'en':'this', 'es':'est-', 'gender':'' },
  {'type':'EsDMorpheme', 'en':'(male)', 'es':'-e', 'gender':'M' },
  {'type':'EsDMorpheme', 'en':'(female)', 'es':'-a', 'gender':'F' },
].map(seed => ({
  ...seed,
  mnemonic: seed.mnemonic || '',
  leafId: 0,
  suspended: false,
})): Array<Leaf>)
