import type { Leaf } from './Leaf'

export default ([
  {'type':'EsN', 'leafId':1,
    'en':'skin', 'es':'piel', 'gender':'F',
    'mnemonic':'skin is burnt and peeled'},
  {'type':'EsN', 'leafId':2,
    'en':'arm', 'es':'brazo', 'gender':'M',
    'mnemonic':'arm tan is bronze'},
  {'type':'EsN', 'leafId':3,
    'en':'leg', 'es':'pierna', 'gender':'F',
    'mnemonic':'leggo my leg or I\'ll pee urine'},
  {'type':'EsN', 'leafId':4,
    'en':'heart', 'es':'corazón', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'leafId':5,
    'en':'stomach', 'es':'estómago', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'leafId':6,
    'en':'eye', 'es':'ojo', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'leafId':7,
    'en':'nose', 'es':'nariz', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'leafId':8,
    'en':'mouth', 'es':'boca', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'leafId':9,
    'en':'ear', 'es':'oreja', 'gender':'F',
    'mnemonic':'ear rings of oreos'},
  {'type':'EsN', 'leafId':10,
    'en':'face', 'es':'cara', 'gender':'F',
    'mnemonic':'face got cut off'},
  {'type':'EsN', 'leafId':11,
    'en':'neck', 'es':'cuello', 'gender':'M',
    'mnemonic':'neck vein was cut way open'},
  {'type':'EsN', 'leafId':12,
    'en':'finger', 'es':'dedo', 'gender':'M',
    'mnemonic':'finger technique by Dedone'},
  {'type':'EsN', 'leafId':13,
    'en':'foot', 'es':'pie', 'gender':'M',
    'mnemonic':'foot stays in the state of PA'},
  {'type':'EsN', 'leafId':14,
    'en':'thigh', 'es':'muslo', 'gender':'M',
    'mnemonic':'thigh-high boots from wild moose'},
  {'type':'EsN', 'leafId':15,
    'en':'ankle', 'es':'tobillo', 'gender':'M',
    'mnemonic':'ankle stung to be young'},
  {'type':'EsN', 'leafId':16,
    'en':'elbow', 'es':'codo', 'gender':'M',
    'mnemonic':'elbow dipped and coated'},
  {'type':'EsN', 'leafId':17,
    'en':'wrist', 'es':'muñeca', 'gender':'F',
    'mnemonic':'wrist watch says \'Moon not yet come!\''},
  {'type':'EsN', 'leafId':18,
    'en':'body', 'es':'cuerpo', 'gender':'M',
    'mnemonic':'body bag for corpse'},
  {'type':'EsN', 'leafId':19,
    'en':'tooth', 'es':'diente', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'leafId':20,
    'en':'hand', 'es':'mano', 'gender':'F',
    'mnemonic':'hand me the manual'},
  {'type':'EsN', 'leafId':21,
    'en':'back', 'es':'espalda', 'gender':'F',
    'mnemonic':'back hair is bald'},
  {'type':'EsN', 'leafId':22,
    'en':'hip', 'es':'cadera', 'gender':'F',
    'mnemonic':'hipster can\'t dare'},
  {'type':'EsN', 'leafId':23,
    'en':'jaw', 'es':'mandíbula', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'leafId':24,
    'en':'shoulder', 'es':'hombro', 'gender':'M',
    'mnemonic':'shoulder on, my brother'},
  {'type':'EsN', 'leafId':25,
    'en':'thumb', 'es':'pulgar', 'gender':'M',
    'mnemonic':'thumb war: push and pull hard'},
  {'type':'EsN', 'leafId':26,
    'en':'tongue', 'es':'lengua', 'gender':'F',
    'mnemonic':'tongue length for languages'},
  {'type':'EsN', 'leafId':27,
    'en':'throat', 'es':'garganta', 'gender':'F',
    'mnemonic':'throat can\'t gargle gargantuan'},
  {'type':'EsD', 'leafId':28,
    'en':'the', 'es':'el', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'leafId':29,
    'en':'the', 'es':'la', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'leafId':32,
    'en':'a', 'es':'un', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'leafId':33,
    'en':'a', 'es':'una', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'leafId':36,
    'en':'my', 'es':'mi', 'gender':'',
    'mnemonic':''},
  {'type':'EsD', 'leafId':38,
    'en':'this', 'es':'este', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'leafId':39,
    'en':'this', 'es':'esta', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'leafId':42,
    'en':'every', 'es':'cada', 'gender':'',
    'mnemonic':''},
].map(leafWithoutSuspended => ({
  ...leafWithoutSuspended,
  suspended: false,
})): Array<Leaf>)
