/* eslint-disable */
import type { Leaf } from './Leaf'

export default (

// Paste the JSON from the export email directly below this line:
[{"type":"N","en":"skin","es":"piel","gender":"F","mnemonic":"skin is burnt and peeled"},
{"type":"N","en":"arm","es":"brazo","gender":"M","mnemonic":"arm armor made of bronze"},
{"type":"N","en":"leg","es":"pierna","gender":"F","mnemonic":"leggo my leg or I'll pee urine"},
{"type":"N","en":"heart","es":"corazón","gender":"M"},
{"type":"N","en":"stomach","es":"estómago","gender":"M"},
{"type":"N","en":"eye","es":"ojo","gender":"M"},
{"type":"N","en":"nose","es":"nariz","gender":"F"},
{"type":"N","en":"mouth","es":"boca","gender":"F"},
{"type":"N","en":"ear","es":"oreja","gender":"F","mnemonic":"ear rings of oreos"},
{"type":"N","en":"face","es":"cara","gender":"F","mnemonic":"face got cut off"},
{"type":"N","en":"neck","es":"cuello","gender":"M","mnemonic":"neck vein was cut way open"},
{"type":"N","en":"finger","es":"dedo","gender":"M","mnemonic":"finger technique by Dedone"},
{"type":"N","en":"foot","es":"pie","gender":"M","mnemonic":"foot stays in the state of PA"},
{"type":"N","en":"thigh","es":"muslo","gender":"M","mnemonic":"thigh-high boots from wild moose"},
{"type":"N","en":"ankle","es":"tobillo","gender":"M","mnemonic":"ankle stung to be young"},
{"type":"N","en":"elbow","es":"codo","gender":"M","mnemonic":"elbow grease coats my coat"},
{"type":"N","en":"wrist","es":"muñeca","gender":"F","mnemonic":"wrist watch says 'Moon not yet come!'"},
{"type":"N","en":"body","es":"cuerpo","gender":"M","mnemonic":"body bag for corpse"},
{"type":"N","en":"tooth","es":"diente","gender":"M"},
{"type":"N","en":"hand","es":"mano","gender":"F","mnemonic":"hand me the manual"},
{"type":"N","en":"back","es":"espalda","gender":"F","mnemonic":"back hair is bald"},
{"type":"N","en":"hip","es":"cadera","gender":"F","mnemonic":"hipster can't dare"},
{"type":"N","en":"jaw","es":"mandíbula","gender":"F","mnemonic":"jaws of gold: “man I got dibs on that”"},
{"type":"N","en":"shoulder","es":"hombro","gender":"M","mnemonic":"shoulder on, bro"},
{"type":"N","en":"thumb","es":"pulgar","gender":"M","mnemonic":"thumb war: push and pull hard"},
{"type":"N","en":"tongue","es":"lengua","gender":"F","mnemonic":"tongue strength from long length "},
{"type":"N","en":"throat","es":"garganta","gender":"F","mnemonic":"throat can't gargle gargantuan"},
{"type":"Det","en":"the","es":"el","gender":"M"},
{"type":"Det","en":"the","es":"la","gender":"F"},
{"type":"Det","en":"a","es":"un","gender":"M"},
{"type":"Det","en":"a","es":"una","gender":"F"},
{"type":"Det","en":"my","es":"mi","gender":""},
{"type":"Det","en":"this","es":"este","gender":"M"},
{"type":"Det","en":"this","es":"esta","gender":"F"},
{"type":"Det","en":"every","es":"cada","gender":""},
{"type":"Inf","en":"ask","es":"preguntar"},
{"type":"Inf","en":"eat","es":"comer"},
{"type":"RegVPattern","en":"1st sing.","infCategory":"AR","tense":"PRES","person":1,"number":1,"es":"-o"},
{"type":"RegVPattern","en":"2nd sing.","infCategory":"AR","tense":"PRES","person":2,"number":1,"es":"-as"},
{"type":"RegVPattern","en":"3rd sing.","infCategory":"AR","tense":"PRES","person":3,"number":1,"es":"-a"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"AR","tense":"PRES","person":1,"number":2,"es":"-amos"},
{"type":"RegVPattern","en":"3rd pl.","infCategory":"AR","tense":"PRES","person":3,"number":2,"es":"-an"},
{"type":"RegVPattern","en":"1st sing.","infCategory":"AR","tense":"PRET","person":1,"number":1,"es":"-é"},
{"type":"RegVPattern","en":"2nd sing.","infCategory":"AR","tense":"PRET","person":2,"number":1,"es":"-aste"},
{"type":"RegVPattern","en":"3rd sing.","infCategory":"AR","tense":"PRET","person":3,"number":1,"es":"-ó"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"AR","tense":"PRET","person":1,"number":2,"es":"-amos"},
{"type":"RegVPattern","en":"3rd pl.","infCategory":"AR","tense":"PRET","person":3,"number":2,"es":"-aron"},
{"type":"RegVPattern","en":"1st sing.","infCategory":"ERIR","tense":"PRES","person":1,"number":1,"es":"-o"},
{"type":"RegVPattern","en":"2nd sing.","infCategory":"ERIR","tense":"PRES","person":2,"number":1,"es":"-es"},
{"type":"RegVPattern","en":"3rd sing.","infCategory":"ERIR","tense":"PRES","person":3,"number":1,"es":"-e"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"ERIR","tense":"PRES","person":3,"number":2,"es":"-en"},
{"type":"RegVPattern","en":"1st sing.","infCategory":"ERIR","tense":"PRET","person":1,"number":1,"es":"-í"},
{"type":"RegVPattern","en":"2nd sing.","infCategory":"ERIR","tense":"PRET","person":2,"number":1,"es":"-iste"},
{"type":"RegVPattern","en":"3rd sing.","infCategory":"ERIR","tense":"PRET","person":3,"number":1,"es":"-ió"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"ERIR","tense":"PRET","person":1,"number":2,"es":"-imos"},
{"type":"RegVPattern","en":"3rd pl.","infCategory":"ERIR","tense":"PRET","person":3,"number":2,"es":"-ieron"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"ER","tense":"PRES","person":1,"number":2,"es":"-emos"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"IR","tense":"PRES","person":1,"number":2,"es":"-imos"},
{"type":"RegVPattern","en":"1st sing.","infCategory":"STEMPRET","tense":"PRET","person":1,"number":1,"es":"-e"},
{"type":"RegVPattern","en":"2nd sing.","infCategory":"STEMPRET","tense":"PRET","person":2,"number":1,"es":"-iste"},
{"type":"RegVPattern","en":"3rd sing.","infCategory":"STEMPRET","tense":"PRET","person":3,"number":1,"es":"-o"},
{"type":"RegVPattern","en":"1st pl.","infCategory":"STEMPRET","tense":"PRET","person":1,"number":2,"es":"-imos"},
{"type":"RegVPattern","en":"3rd pl.","infCategory":"STEMPRET","tense":"PRET","person":3,"number":2,"es":"-ieron"}]

.map(seed => ({
  ...seed,
  mnemonic: seed.mnemonic || '',
  leafId: 0,
  suspended: false,
})): Array<Leaf>)
