import type { Card } from './Card'

export default ([
  {'type':'EsN', 'cardId':1,
    'en':'skin', 'es':'piel', 'gender':'F',
    'mnemonic':'skin is burnt and peeled'},
  {'type':'EsN', 'cardId':2,
    'en':'arm', 'es':'brazo', 'gender':'M',
    'mnemonic':'arm tan is bronze'},
  {'type':'EsN', 'cardId':3,
    'en':'leg', 'es':'pierna', 'gender':'F',
    'mnemonic':'leggo my leg or I\'ll pee urine'},
  {'type':'EsN', 'cardId':4,
    'en':'heart', 'es':'corazón', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'cardId':5,
    'en':'stomach', 'es':'estómago', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'cardId':6,
    'en':'eye', 'es':'ojo', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'cardId':7,
    'en':'nose', 'es':'nariz', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'cardId':8,
    'en':'mouth', 'es':'boca', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'cardId':9,
    'en':'ear', 'es':'oreja', 'gender':'F',
    'mnemonic':'ear rings of oreos'},
  {'type':'EsN', 'cardId':10,
    'en':'face', 'es':'cara', 'gender':'F',
    'mnemonic':'face got cut off'},
  {'type':'EsN', 'cardId':11,
    'en':'neck', 'es':'cuello', 'gender':'M',
    'mnemonic':'neck vein was cut way open'},
  {'type':'EsN', 'cardId':12,
    'en':'finger', 'es':'dedo', 'gender':'M',
    'mnemonic':'finger technique by Dedone'},
  {'type':'EsN', 'cardId':13,
    'en':'foot', 'es':'pie', 'gender':'M',
    'mnemonic':'foot stays in the state of PA'},
  {'type':'EsN', 'cardId':14,
    'en':'thigh', 'es':'muslo', 'gender':'M',
    'mnemonic':'thigh-high boots from wild moose'},
  {'type':'EsN', 'cardId':15,
    'en':'ankle', 'es':'tobillo', 'gender':'M',
    'mnemonic':'ankle stung to be young'},
  {'type':'EsN', 'cardId':16,
    'en':'elbow', 'es':'codo', 'gender':'M',
    'mnemonic':'elbow dipped and coated'},
  {'type':'EsN', 'cardId':17,
    'en':'wrist', 'es':'muñeca', 'gender':'F',
    'mnemonic':'wrist watch says \'Moon not yet come!\''},
  {'type':'EsN', 'cardId':18,
    'en':'body', 'es':'cuerpo', 'gender':'M',
    'mnemonic':'body bag for corpse'},
  {'type':'EsN', 'cardId':19,
    'en':'tooth', 'es':'diente', 'gender':'M',
    'mnemonic':''},
  {'type':'EsN', 'cardId':20,
    'en':'hand', 'es':'mano', 'gender':'F',
    'mnemonic':'hand me the manual'},
  {'type':'EsN', 'cardId':21,
    'en':'back', 'es':'espalda', 'gender':'F',
    'mnemonic':'back hair is bald'},
  {'type':'EsN', 'cardId':22,
    'en':'hip', 'es':'cadera', 'gender':'F',
    'mnemonic':'hipster can\'t dare'},
  {'type':'EsN', 'cardId':23,
    'en':'jaw', 'es':'mandíbula', 'gender':'F',
    'mnemonic':''},
  {'type':'EsN', 'cardId':24,
    'en':'shoulder', 'es':'hombro', 'gender':'M',
    'mnemonic':'shoulder on, my brother'},
  {'type':'EsN', 'cardId':25,
    'en':'thumb', 'es':'pulgar', 'gender':'M',
    'mnemonic':'thumb war: push and pull hard'},
  {'type':'EsN', 'cardId':26,
    'en':'tongue', 'es':'lengua', 'gender':'F',
    'mnemonic':'tongue length for languages'},
  {'type':'EsN', 'cardId':27,
    'en':'throat', 'es':'garganta', 'gender':'F',
    'mnemonic':'throat can\'t gargle gargantuan'},
  {'type':'EsD', 'cardId':28,
    'en':'the', 'es':'el', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':29,
    'en':'the', 'es':'la', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':30,
    'en':'the', 'es':'los', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':31,
    'en':'the', 'es':'las', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':32,
    'en':'a', 'es':'un', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':33,
    'en':'a', 'es':'una', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':34,
    'en':'some', 'es':'unos', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':35,
    'en':'some', 'es':'unas', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':36,
    'en':'my', 'es':'mi', 'gender':'',
    'mnemonic':''},
  {'type':'EsD', 'cardId':37,
    'en':'my', 'es':'mis', 'gender':'',
    'mnemonic':''},
  {'type':'EsD', 'cardId':38,
    'en':'this', 'es':'este', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':39,
    'en':'this', 'es':'esta', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':40,
    'en':'these', 'es':'estos', 'gender':'M',
    'mnemonic':''},
  {'type':'EsD', 'cardId':41,
    'en':'these', 'es':'estas', 'gender':'F',
    'mnemonic':''},
  {'type':'EsD', 'cardId':42,
    'en':'every', 'es':'cada', 'gender':'',
    'mnemonic':''},
  {'type':'EsD', 'cardId':43,
    'en':'two', 'es':'dos', 'gender':'',
    'mnemonic':''},
  {'type':'EsD', 'cardId':44,
    'en':'three', 'es':'tres', 'gender':'',
    'mnemonic':''}
].map(cardWithoutSuspended => ({
  ...cardWithoutSuspended,
  suspended: false,
})): Array<Card>)
